language: python

python:
  - 3.5

before_install:
  - sudo apt-get install ngspice
  - sudo apt-get install libfftw3-3
  - git clone https://github.com/imr/ngspice
  - cd ngspice
  - mkdir release
  - cd release
  - ../configure --with-ngshared
  - make
  - sudo make install 
  - cd ../../
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
# command to run tests
script: 
    - py.test --cov

after_success:
    - coveralls

