language: python

python:
  - 3.5

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
# command to run tests
script: 
    - py.test --cov=ngspicepy

after_success:
    - coveralls

