"""The netlist class."""
import ngspicepy as ng

from ngspicepy.ngspicepy import __parse__
import os

import string


class Netlist(object):
    """A class that represents SPICE netlists."""

    def __init__(self, netlist):
        """Class constructor.

        Parameters
        ----------
            1. A string file (with path) of the netlist file.
            2. A string containing the netlist with each line separated by a
            newline.
            3. A list of strings, where each item is a line of the netlist.
        """
        if type(netlist) == str:
            if os.path.isfile(netlist):
                with open(netlist) as f:
                    netlist_list = f.readlines()
            elif '\n' in netlist:
                netlist_list = netlist.split('\n')
            else:
                raise ValueError('Invalid netlist file or string')
        elif type(netlist) == list:
            netlist_list = netlist
        else:
            raise TypeError('Netlist format unsupported.\
                    Must be a string or list')

        self.netlist = [item.strip()
                        for item in netlist_list
                        if item.strip() != '']

        self.__checkNetlist__()

    def setup_sim(self, sim_type, *args, **kwargs):
        """Set up the simulation.
        
        Parameters
        ----------
        sim_type
            The type of the simulation
        *args
            The simulation parameters as arguments
        **kwargs
            The simulation parameters as keyword arguments
        
        Examples
        --------
        >>> setup_sim('dc','v1 0 1 .3')
        >>> setup_sim('ac','dec 10 1 10')
        >>> setup_sim('tran','1 10')
        """
        self.sim_type = sim_type
        if self.sim_type == 'op':
            self.parsed_args = []
        else:
            self.parsed_args = __parse__(sim_type, *args, **kwargs)

    def run(self):
        """Run the simulation.

        Depending on the arguments set in the set_simu() this function simply
        run that simulation.
        """
        ng.load_netlist(self.netlist)
        ng.send_command(self.sim_type + ' ' + ' '.join(self.parsed_args))

    def get_current_plot(self):
        """Return the name of the latest plot."""
        return ng.current_plot()

    def get_plots(self):
        """Return a list of plot names.

        A plot is the name for a group of vectors.
        
        Example
        -------
        A DC simulation run right after ngspice is loaded creates a plot called
        dc1 which contains the vectors generated by the DC simulation.
        """
        return ng.get_plot_names()

    def get_vector_names(self, plot_name):
        """Return a list of the names of the vectors in the given plot.
        
        Parameters
        ----------
        plot_name
            It specifies the plot whose vectors need to be returned. If it
            unspecified, the vector names from the current plot are returned.
        """
        return ng.get_vector_names(plot_name)

    def get_vector(self, vector_name, plot_name):
        """Enable the user to get the data available in a given vector.
        
        Parameters
        ----------
        vector_arg
            It specifies name of the vector.
        plot_agr
            It specifies the name of the plot.
        """
        return ng.get_data(vector_name, plot_name)

    def get_vectors(self, plot_name):
        """Return a dictionary of all vectors in the specified plot.
        
        Parameter
        ---------
        plot_name
            It specifies the name of the plot.
        """
        return ng.get_all_data(plot_name)

    def __checkNetlist__(self):
        """Check if the netlist is valid."""
        # Check if the line has a valid component or is a valid command.
        # Ignore line 1 since its a title line

        valid_components = string.ascii_uppercase

        valid_commands = ['OPTIONS',  # Simulator variables
                          'NODESET',  # Specify initial node voltage guesses
                          'IC',       # Set initial conditions
                          'AC',       # Small signal AC analysis
                          'DC',       # DC transfer function
                          'DISTO',    # Distortion analysis
                          'NOISE',    # Noise analysis
                          'OP',       # Operating point analysis
                          'PZ',       # Pole-zero analysis
                          'SENS',     # DC or small-signal AC sensitivity
                                      # analysis
                          'TF',       # Transfer function analysis
                          'TRAN',     # Transient analysis
                          'PSS',      # Periodic steady state analysis
                          'MEAS',     # Measurements after AC, DC and
                          'MEASURE',  # transient analysis
                          'SAVE',     # Name vectors to be saved in raw file
                          'PRINT',    # Print vectors
                          'PLOT',     # Plot vectors
                          'FOUR',     # Fourier analysis of transient analysis
                                      # output
                          'PROBE',    # Same as SAVE
                          'WIDTH',    # Set print/plot width
                          'TITLE',    # Title of the netlist
                          'END',      # End of netlist
                          'MODEL',    # Component's model
                          'SUBCKT',   # Begingging of sub circuit definition
                          'ENDS',     # End of sub circuit definition
                          'GLOBAL',   # Global nodes
                          'INCLUDE',  # Include a file
                          'LIB',      # Include a library
                          'PARAM',    # Netlist parameters
                          'FUNC',     #
                          'CSPARAM',  #
                          'TEMP',     # Set temperature
                          'IF']       #

        ignore_first_chars = '*+'

        valid_first_chars = valid_components + ignore_first_chars

        inControl = False

        netlist = self.netlist[1:]
        for idx, line in enumerate(netlist, start=2):
            # Detect if we're in a control block
            command = line.split()[0].upper()
            if command == '.CONTROL':
                inControl = True
            elif command == '.ENDC':
                inControl = False
                continue

            if not inControl:
                # Check if line is a valid component.
                if line[0] != '.' and line[0].upper() not in valid_first_chars:
                    raise ValueError("Unable to parse line " + str(idx) +
                                     "unknown component '" + line[0] +
                                     "':\n" + line)
                # Check if it is a valid command
                elif line[0] == '.':
                    command  = line[1:].split()[0].upper()  # First word after
                                                            # the dot is the
                                                            # command
                    # Ensure the command is valid
                    if command not in valid_commands:
                        raise ValueError("Unable to parse line " + str(idx) +
                                         "unknown command '" + 
                                         command + "':\n" +
                                         line)

    def __str__(self):
        r"""Return the netlist followed by next line character."""
        return '\n'.join(self.netlist)
